; Script generated by HM NIS Edit
Name "Map-Concator-App"

; Define Version
!define VERSION 0.0.8

; Define Icon Filepath
!define ICON_FILE "media\dev_logo.ico"

OutFile "installers\Map-Concator-App-Installer-${VERSION}.exe"
Icon "${ICON_FILE}"

InstallDir "$PROGRAMFILES\Map-Concator-App"

; Pages 
Page directory
Page instfiles

; Sections
Section
    SetOutPath $INSTDIR 
    File /r "build\exe.win-amd64-3.11\*"
SectionEnd

; Start Menu Shortcuts
;Section
;    CreateDirectory "$SMPROGRAMS\Map-Concator-App"
;    CreateShortCut "$SMPROGRAMS\Map-Concator-App\Uninstall.lnk" "$INSTDIR\uninstall.exe"
;    CreateShortCut "$SMPROGRAMS\Map-Concator-App\Map-Concator-App.lnk" "$INSTDIR\Map-Concator-App.exe"
;SectionEnd

Section
    SetShellVarContext all
    ;CreateDirectory "$DESKTOP\Map-Concator-App"
    CreateShortCut "$DESKTOP\Map-Concator-App.lnk" "$INSTDIR\Map-Concator-App.exe"
    ;CreateShortCut "$DESKTOP\Map-Concator-App\Uninstall.lnk" "$INSTDIR\uninstall.exe"     ; not needed as it can be uninstalled from Program under Control Panel
    WriteUninstaller "$INSTDIR\Uninstall.exe"

    ; Add entry to Programs and Features (Uninstall registry)
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Map-Concator-App" "DisplayName" "Map-Concator-App"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Map-Concator-App" "UninstallString" "$\"$INSTDIR\uninstall.exe$\""
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Map-Concator-App" "Publisher" "Ramlaxman-Group"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Map-Concator-App" "DisplayIcon" "$\"$INSTDIR\Map-Concator-App.exe$\""
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Map-Concator-App" "DisplayVersion" "${VERSION}"
SectionEnd

; Uninstaller
UninstallText "Uninstalling Map-Concator-App"
Section "Uninstall"
    SetShellVarContext all
    Delete "$DESKTOP\Map-Concator-App.lnk"   ; Remove shortcuts
    Delete "$INSTDIR\Map-Concator-App.exe"  ; Delete installed files
    RMDir /r /REBOOTOK "$INSTDIR"     ; Remove installation directory

    DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Map-Concator-App" ; Remove registry entries
    MessageBox MB_OK "Application Uninstalled."
SectionEnd
